[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    # Do not fail the build if a11y issues are found
    failWithIssues = false
    # Perform a11y check against WCAG 2.1 AAA
    wcagLevel = 'WCAG2AAA'
